extends:
  - stylelint-config-standard
  - stylelint-config-tailwindcss
  - stylelint-config-prettier
  - stylelint-order
rules:
  # Tailwind CSS
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - tailwind
        - apply
        - variants
        - responsive
        - screen
  # Customize property order:
  order/order:
    - custom-properties
    - declarations
  order/properties-alphabetical-order: true
